version: '3.0'

services:
    zabbix-frontend:
        image: zabbix/zabbix-web-apache-mysql:alpine-6.0-latest
        container_name: zabbix-web
        environment:
            - ZBX_SERVER_HOST=zabbix-server
            - ZBX_SERVER_PORT=10051
            - DB_SERVER_HOST=zabbix-db
            - DB_SERVER_PORT=3306
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=root
            - MYSQL_PASSWORD=PleaseUseAVerifySecureP4ssw0rd
            - PHP_TZ=America/Sao_Paulo
        depends_on:
            - zabbix-server
            - zabbix-db
        links:
            - zabbix-server
            - zabbix-db
        ports:
                - '127.0.0.1:8080:8080'
        restart: always

    zabbix-server:
        image: zabbix/zabbix-server-mysql:alpine-6.0-latest
        container_name: zabbix-server
        environment:
            - DB_SERVER_HOST=zabbix-db
            - DB_SERVER_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=PleaseUseAVerifySecureP4ssw0rd
        ports:
            - '10051:10051'
        links:
            - zabbix-db
        depends_on:
            - zabbix-db
        restart: always

    zabbix-db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: zabbix-db
        environment:
            - MYSQL_ROOT_PASSWORD=PleaseUseAVerifySecureP4ssw0rd
        ports:
                - '127.0.0.1:3306:3306'
        restart: always

